export const FormSeed = [
  { formNumber: "1" },
  { formNumber: "2" },
  { formNumber: "3" },
  { formNumber: "4" },
  { formNumber: "5" },
  { formNumber: "6" },
  { formNumber: "7" },
  { formNumber: "8" },
  { formNumber: "9" },
  { formNumber: "10" },
  { formNumber: "11" },
  { formNumber: "12" },
  { formNumber: "13" },
  { formNumber: "14" },
];
